name="Ali Ali Ahmad!!!!"
print(name.endswith("!!!"))
print(name.startswith("Ali"))
print(name.count("Ali"))
# print(name.lowercase())
print(name.istitle())
print(name.replace("Ali","Ahmad"))
print(name.rstrip("!"))
print(name.center(50))
print(len(name))
print(len(name.center(50)))
print(name.find("Ahmad"))
print(name.capitalize())
print(name.islower())
print(name.isprintable())
print(name.isalnum)